//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meds
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int id { get; set; }
        public int drugID { get; set; }
        public int pharID { get; set; }
        public double price { get; set; }
        public int count { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
